name: Deploy Node.js Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código (versão mais recente do Node.js 20)
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Node.js (use a versão Node.js 20 diretamente)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Instalar dependências
    - name: Install dependencies
      run: npm install

    # Criar o arquivo ZIP para Lambda
    - name: Create Lambda ZIP
      run: |
        zip -r build.zip .
        mv build.zip terraform/

    # Configurar Terraform (versão mais recente do Node.js 20)
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    # Inicializar Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    # Aplicar Terraform (criação de recursos na AWS)
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
