name: Deploy Node.js Lambda

on:
  push:
    branches:
      - main  # A branch que vai disparar a pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Criar o arquivo ZIP para Lambda
      - name: Create Lambda ZIP
        run: |
          zip -r lambda.zip .
          # Se você for usar o S3:
          aws s3 cp lambda.zip s3://meu-bucket-s3/path/to/lambda.zip
          # Se for usar o upload direto:
          aws lambda update-function-code --function-name my_lambda_function --zip-file fileb://lambda.zip

      # Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      # Inicializar Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Aplicar Terraform (criação de recursos na AWS)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
