name: Deploy Node.js Lambda

on:
  push:
    branches:
      - main  # A branch que vai disparar a pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Criar o arquivo ZIP para Lambda
      - name: Create Lambda ZIP
        run: |
          zip -r lambda.zip .
          # Configurar as credenciais da AWS para o AWS CLI
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1  # Ajuste a região conforme necessário

      # Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      # Inicializar Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Aplicar Terraform (criação de recursos na AWS)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Obter o nome do bucket gerado pelo Terraform
      - name: Get Bucket Name
        id: get_bucket_name
        run: |
          BUCKET_NAME=$(terraform output -raw bucket_name)
          echo "Bucket name is $BUCKET_NAME"
          echo "::set-output name=bucket_name::$BUCKET_NAME"

      # Upload do arquivo ZIP para o S3
      - name: Upload Lambda ZIP to S3
        run: |
          # Usando o nome do bucket obtido pelo Terraform
          aws s3 cp lambda.zip s3://${{ steps.get_bucket_name.outputs.bucket_name }}/path/to/lambda.zip
